---
title: "WCC City Highways - Dedicated LCCP"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    logo: logo.png
    favicon: logo.png
    css: styles.css
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(lubridate)
library(leaflet)
library(readr)
library(sf)
library(readxl)
library(leafgl)
library(stringr)
```

```{r data_processing, results='hide'}
# Westminster Wards
wards <- read_sf("../../../data/clean_data_files/westminster_boundary_files/London-wards-2018/London-wards-2018_ESRI/London_Ward.shp")
wards <- wards %>% 
  dplyr::filter(DISTRICT == "City of Westminster") %>%
  select(NAME)


corrections <- read_excel("~/Documents/WestminsterPosition/organised/Dedicated_LCCP/LocationAllocation/2021 - 05 - 24 Proposed 400 Dedicated Res Bays.xlsx")

corrections <- read_excel("LCCP Action Log - Active.xlsx", sheet="Pending Dedicated EV Res Bays")

corrections <- corrections %>% 
  tidyr::replace_na(list(`Bay Position in Lot`="Site Check Required")) %>%
  dplyr::filter(`Bay Position in Lot` != "Remove") %>%
  mutate(id=paste(str_to_lower(`Site Name`), str_to_lower(`Lamp Col No`), sep="_")) %>%
  select(`L-EV Charge Point ID`, id, `Site Name`, `Lamp Col No`, `Feat Loc`, `Cent East`, 
         `Cent North`, `Bay Position in Lot`, `WCC Site Comments`) %>%
  rename(ChargepointID = `L-EV Charge Point ID`, LocationName=`Site Name`, FeatureLocation = `Feat Loc`)
  
corrections$labs <- sapply(seq(nrow(corrections)), function(i) {
  paste0( '<p><strong>', corrections[i, "LocationName"], '</strong></p><hr></hr><p><strong>Feature: </strong>',
          corrections[i, "FeatureLocation"], '</p><p><strong>Chargepoint ID: </strong>',
          corrections[i, "ChargepointID"], '</p><p><strong>Comments: </strong>',
          corrections[i, "WCC Site Comments"], '</p><p><strong>Bay Location: </strong>',
          corrections[i, "Bay Position in Lot"],'</p>')
})

corrections <- corrections %>%
  dplyr::filter(!is.na(`Cent East`)) %>%
  st_as_sf(coords=c("Cent East", "Cent North"), crs=27700) %>%
  st_intersection(wards) %>%
  st_transform(4326)


ded_sugg <- corrections

# Lamp Column Charge Points
ded_ids <-  c("suby1100002553", "suby1100002508", "suby1100002584", "suby1100003290", "suby1100003264", "suby1100002591",
              "suby1100002559", "steob100000791", "suby1100002500", "suby1100002581", "suby1100003842", "suby1100002879",
              "suby1100002888", "suby1100002501", "suby1100002628", "suby1100002820", "suby1100002715", "suby1100002436",
              "suby1100002366", "suby1100002382", "suby1100002429", "suby1100003075", "suby1100002693", "suby1100002354",
              "suby1100002481", "suby1100002358")

lccp <- read_excel("../../../../ElectricVehicles/Data/LocationData/2022 - 02 Electric Charge Point Master Asset List.xlsx", skip=1) %>% mutate(id=paste(str_to_lower(`Site Name`), str_to_lower(`Lamp Col No`), sep="_"))
lccp <- lccp %>%
  dplyr::filter(!id %in% ded_sugg$id) %>%
  dplyr::filter(`L-EV Charge Manufacturer`=="Ubitricity") %>%
  st_as_sf(coords=c("Cent East", "Cent North"), crs=27700) %>%
  st_intersection(wards) %>%
  st_transform(4326) 

existing_dedicated <- lccp %>% dplyr::filter(tolower(L.EV.Charge.Point.ID) %in% ded_ids)
lccp <- lccp %>% dplyr::filter(!tolower(L.EV.Charge.Point.ID) %in% ded_ids)

lccp$nearest_feature_id <- st_nearest_feature(st_transform(lccp,27700), st_transform(ded_sugg, 27700))
lccp$distance <- NA
for (i in 1:nrow(lccp)){
  lccp$distance[i] <- st_distance(lccp[i,], ded_sugg[lccp$nearest_feature_id[i], ])
}

lccp <- lccp %>% dplyr::filter(distance > 2)

# Bay Lines
bays <- read_sf("../../../data/clean_data_files/parking_bays/order_lines/OrderLines.shp")

bays <- bays %>%
  dplyr::filter(is.na(DATE_TO)) %>%
  dplyr::filter(ORDER_TYPE %in% c("Shared Use Bay", "Resident Bay", "Visitor Shared Use Bay",
                                  "Electric Vehicle Charging Bay", "Electric Vehicle Resident Bay")) %>%
  st_intersection(wards) %>%
  st_transform(4326) 

wards <- wards %>% st_transform(4326)
```

Full Map {data-icon="fa-map"}
=====================================  

### Page 1 {.no-padding .no-title}

```{r full_map}
addLegendCustom <- function(map, colors, labels, sizes, opacity = 1, position="bottomleft"){
  colorAdditions <- paste0(colors, "; width:", sizes, "px; height:", sizes, "px")
  labelAdditions <- paste0("<div style='display: inline-block;height: ", sizes, "px;margin-top: 4px;line-height: ", sizes, "px;'>", labels, "</div>")

  return(addLegend(map, colors = colorAdditions, labels = labelAdditions, opacity = opacity, position=position))
}

leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron, group="Map", options = providerTileOptions(maxZoom = 24)) %>%
  addProviderTiles(providers$Esri.WorldImagery, group="Satellite") %>%
  addTiles(group="OSM") %>%
  addPolygons(data=wards, fillOpacity = 0, weight = 1, color = "black", opacity = 1) %>%
  addGlPolylines(data=bays %>% sf::st_cast("LINESTRING"), color = "darkgreen", weight = 0.8, group="Bay Lines") %>%
  addCircleMarkers(data=lccp, stroke=F, radius = 3, fillOpacity = 1, fillColor = "black", group="LCCP Not Dedicated", label=~paste(L.EV.Charge.Point.ID, Site.Name, Feat.Loc, sep=" : ")) %>%
  addCircleMarkers(data=ded_sugg, stroke=F, radius = 3, fillOpacity = 1, fillColor = "blue", group="LCCP To Dedicate", label=~paste(ChargepointID, LocationName, FeatureLocation, sep=" : "), popup=~labs) %>%
  addCircleMarkers(data=existing_dedicated, stroke=F, radius = 3, fillOpacity = 1, fillColor = "red", group="Existing Dedicated", label=~paste(L.EV.Charge.Point.ID, Site.Name, Feat.Loc, sep=" : ")) %>%
  addLayersControl(overlayGroups = c("LCCP Not Dedicated", "LCCP To Dedicate", "Existing Dedicated", "Bay Lines"), baseGroups = c("Map", "Satellite", "OSM"), options=layersControlOptions(collapsed = FALSE)) %>%
  addMeasure(primaryLengthUnit = "meters", secondaryLengthUnit = "feet", position="topleft") %>%
  addLegendCustom(colors = c("blue", "black", "red", "green"), labels = c("Bay To Dedicated", "Not Dedicated", "Existing Dedicated",  "Bay Lines"), sizes = c(20, 20, 20, 20)) 


```


```{r ward_maps_function}
#requests_ward <- read.csv("../../../data/clean_data_files/requests/ward_summary.csv")

plot_map <- function(ward){
  
  ward_polygon <- wards %>% dplyr::filter(NAME %in% ward) 
  
  # Stats
  
  bays_ward <- bays %>% dplyr::filter(NAME %in% ward)
  
  ded_sugg_ward <- ded_sugg %>% dplyr::filter(NAME %in% ward) %>% mutate(Colour="blue", 
                                                                         Group="LCCP To Dedicate",
                                                                         labs=paste(ChargepointID, LocationName, FeatureLocation, sep=" : "))
  
  lccp_ward <- lccp %>% dplyr::filter(NAME %in% ward) %>% mutate(Colour="black", 
                                                                 Group="LCCP Not Dedicated",
                                                                 labs=paste(L.EV.Charge.Point.ID, Site.Name, Feat.Loc, sep=" : "))
  
  existing_dedicated_ward <- existing_dedicated %>% dplyr::filter(NAME %in% ward) %>% mutate(Colour="red", 
                                                                                             Group="Existing Dedicated",
                                                                                             labs=paste(L.EV.Charge.Point.ID, Site.Name, Feat.Loc, sep=" : "))

  combined <- bind_rows(ded_sugg_ward, lccp_ward, existing_dedicated_ward)
  
leaflet() %>%
    addProviderTiles(providers$CartoDB.Positron, group="Map", options = providerTileOptions(maxZoom = 24)) %>%
    addProviderTiles(providers$Esri.WorldImagery, group="Satellite") %>%
    addTiles(group="OSM") %>%
    addPolygons(data=ward_polygon, fillOpacity = 0, weight = 1, color = "black", opacity = 1) %>%
    addGlPolylines(data=bays_ward %>% sf::st_cast("LINESTRING"), color = "darkgreen", weight = 0.8, group="Bay Lines") %>%
    #addCircleMarkers(data=lccp_ward, stroke=F, radius = 3, fillOpacity = 1, fillColor = "black", group="LCCP Not Dedicated", label=~paste(L.EV.Charge.Point.ID, Site.Name, Feat.Loc, sep=" : ")) %>%
    addCircleMarkers(data=combined, stroke=F, radius = 3, fillOpacity = 1, fillColor = ~Colour, group=~Group, label=~labs) %>%
  #addCircleMarkers(data=existing_dedicated_ward, stroke=F, radius = 3, fillOpacity = 1, fillColor = "red", group="Existing Dedicated", label=~paste(L.EV.Charge.Point.ID, Site.Name, Feat.Loc, sep=" : ")) %>%
    addLayersControl(overlayGroups = c("LCCP Not Dedicated", "LCCP To Dedicate", "Existing Dedicated", "Bay Lines"), baseGroups = c("Map", "Satellite", "OSM"), options=layersControlOptions(collapsed = FALSE)) %>%
    addMeasure(primaryLengthUnit = "meters", secondaryLengthUnit = "feet", position="topleft") %>%
  addLegendCustom(colors = c("blue", "black", "red", "green"), labels = c("Bay To Dedicated", "Not Dedicated", "Existing Dedicated",  "Bay Lines"), sizes = c(15, 15, 15, 15), position="bottomleft") 
      
}


```


```{r ward_maps}
ward_names <- sort(wards$NAME)
out <- lapply(seq_along(ward_names), function(i) {

  a1 <- knitr::knit_expand(text = sprintf("\n%s {data-navmenu=\"Wards\" data-icon=\"fa-bars\"}", ward_names[[i]])) # tab header, auto extracts names of `hcs`
  a2 <- knitr::knit_expand(text = sprintf("\n=====================================\n"))
  a3 <- knitr::knit_expand(text = sprintf("\n### %s {.no-padding}\n", ward_names[[i]]))
  a4 <- knitr::knit_expand(text = "\n```{r}") # start r chunk
  a5 <- knitr::knit_expand(text = sprintf("\nplot_map(\"%s\")\n", ward_names[[i]])) # extract graphs by "writing" out `hcs[[1]]`, `hcs[[2]]` etc. to be rendered later
  a6 <- knitr::knit_expand(text = "\n```\n") # end r chunk

  paste(a1, a2, a3, a4, a5, a6, collapse = '\n') # collapse together all lines with newline separator

})
cat("\n")
cat("\n")
```

`r paste(knitr::knit(text = paste(out, collapse = '\n')))`

About {data-icon="fa-bars"}
===================================== 

#### Dedicated Lamp Column Charge Points

* Author: Westminster City Highways
* Date Created: 2021-05-14
* Date Updated: `r lubridate::today()`

<!-- Description of Report -->

This map shows the planned expansion of EV dedicated bays alongside lamp column charge points.
